version: "3.9"

services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: Production
      VITE_API_BASE_URL: https://localhost/api
    restart: always

  backend:
    environment:
      - BUILD_CONFIGURATION=Production
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always

  nginx:
    ports: !override
      - "80:80"
      - "443:443"
    restart: always
    environment:
      - BUILD_CONFIGURATION=Production