FROM node:22-alpine

ARG VITE_API_BASE_URL=https://localhost/api
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
RUN npm i -g vite
RUN npm i -g typescript
RUN npm i -g serve
RUN npm install
COPY . .
RUN npm run build

EXPOSE 3000
CMD [ "serve", "-s", "dist" ]