# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: '3.1'
services:
  database:
    image: postgres:14.6
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    user: postgres
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_PASSWORD=mot-de-passe
    ports:
      - 5433:5432
    volumes:
      - ./Database/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      #- ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
