# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: '3.1'
services:
  nginx:
    image: nginx
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8082:80
    volumes:
      - ../config/nginx/nginx-test.conf:/etc/nginx/nginx.conf:ro
